### ISSUE TITLE
cargo build --release failed：could not find `sync` in `ark_std`

### ISSUE THREAD

**Issue by yizhihuaqi** [scipr-lab/zexe#377]
when I run `cargo build --release` ，it reports error：`could not find 'sync' in 'ark_std' `.

**Comment by Rajil1213** [comment]
Ran into a similar issue while building another `ark-` package and solved it by adding the `std` patch in `Cargo.toml`:

```toml
[patch.crates-io]
ark-std = { git = "https://github.com/arkworks-rs/std/" }
```
